# Generated by Django 5.0.3 on 2024-04-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='submited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
